#!/bin/bash

# Output file
output_file="./interop/lib/all.d.ts"

# List of files to concatenate
files=(
    "./interop/lib/lib.es5.d.ts"
    "./interop/lib/lib.es6.d.ts"
    "./interop/lib/lib.es2015.core.d.ts"
    "./interop/lib/lib.es2015.promise.d.ts"
    "./interop/lib/lib.es2015.proxy.d.ts"
    "./interop/lib/lib.es2015.reflect.d.ts"
    "./interop/lib/lib.es2015.symbol.d.ts"
    "./interop/lib/lib.es2015.symbol.wellknown.d.ts"
    "./interop/lib/lib.es2015.generator.d.ts"
    "./interop/lib/lib.es2015.iterable.d.ts"
    "./interop/lib/lib.es2015.collection.d.ts"
    "./interop/lib/lib.es2015.d.ts"
    "./interop/lib/lib.es2016.array.include.d.ts"
    "./interop/lib/lib.es2016.d.ts"
    "./interop/lib/lib.es2016.intl.d.ts"
    "./interop/lib/lib.es2017.object.d.ts"
    "./interop/lib/lib.es2017.sharedmemory.d.ts"
    "./interop/lib/lib.es2017.string.d.ts"
    "./interop/lib/lib.es2017.typedarrays.d.ts"
    "./interop/lib/lib.es2017.date.d.ts"
    "./interop/lib/lib.es2017.intl.d.ts"
    "./interop/lib/lib.es2017.d.ts"
    "./interop/lib/lib.es2018.promise.d.ts"
    "./interop/lib/lib.es2018.regexp.d.ts"
    "./interop/lib/lib.es2018.asyncgenerator.d.ts"
    "./interop/lib/lib.es2018.asynciterable.d.ts"
    "./interop/lib/lib.es2018.intl.d.ts"
    "./interop/lib/lib.es2018.d.ts"
    "./interop/lib/lib.es2019.array.d.ts"
    "./interop/lib/lib.es2019.intl.d.ts"
    "./interop/lib/lib.es2019.object.d.ts"
    "./interop/lib/lib.es2019.string.d.ts"
    "./interop/lib/lib.es2019.symbol.d.ts"
    "./interop/lib/lib.es2019.d.ts"
    "./interop/lib/lib.es2020.bigint.d.ts"
    "./interop/lib/lib.es2020.date.d.ts"
    "./interop/lib/lib.es2020.intl.d.ts"
    "./interop/lib/lib.es2020.number.d.ts"
    "./interop/lib/lib.es2020.promise.d.ts"
    "./interop/lib/lib.es2020.sharedmemory.d.ts"
    "./interop/lib/lib.es2020.string.d.ts"
    "./interop/lib/lib.es2020.symbol.wellknown.d.ts"
    "./interop/lib/lib.es2020.d.ts"
    "./interop/lib/lib.es2021.weakref.d.ts"
    "./interop/lib/lib.es2021.intl.d.ts"
    "./interop/lib/lib.es2021.promise.d.ts"
    "./interop/lib/lib.es2021.string.d.ts"
    "./interop/lib/lib.es2021.d.ts"
    "./interop/lib/lib.es2022.error.d.ts"
    "./interop/lib/lib.es2022.intl.d.ts"
    "./interop/lib/lib.es2022.object.d.ts"
    "./interop/lib/lib.es2022.regexp.d.ts"
    "./interop/lib/lib.es2022.sharedmemory.d.ts"
    "./interop/lib/lib.es2022.string.d.ts"
    "./interop/lib/lib.es2022.array.d.ts"
    "./interop/lib/lib.es2022.d.ts"
    "./interop/lib/lib.es2023.intl.d.ts"
    "./interop/lib/lib.es2023.array.d.ts"
    "./interop/lib/lib.es2023.collection.d.ts"
    "./interop/lib/lib.es2023.d.ts"
    "./interop/lib/lib.esnext.intl.d.ts"
    "./interop/lib/lib.esnext.array.d.ts"
    "./interop/lib/lib.esnext.collection.d.ts"
    "./interop/lib/lib.esnext.decorators.d.ts"
    "./interop/lib/lib.esnext.disposable.d.ts"
    "./interop/lib/lib.esnext.object.d.ts"
    "./interop/lib/lib.esnext.promise.d.ts"
    "./interop/lib/lib.esnext.regexp.d.ts"
    "./interop/lib/lib.esnext.string.d.ts"
    "./interop/lib/lib.esnext.d.ts"
    "./interop/lib/lib.esnext.full.d.ts"
)

# Remove the output file if it exists
rm -f "$output_file"

# Concatenate all files into the output file
for file in "${files[@]}"; do
    cat "$file" >> "$output_file"
    echo -e "\n" >> "$output_file"  # Add a newline between files for separation
done

echo "All files have been concatenated into $output_file"
